import Link from "next/link";
import { BadgeCheck, Clock3, Heart, ShieldCheck, Truck } from "lucide-react";
import type { Product } from "@/domain/models";
import { Breadcrumb } from "@/components/ui/Breadcrumb";
import { Container } from "@/components/ui/Container";
import { RatingStars } from "@/components/ui/RatingStars";
import { TrustBar } from "@/components/layout/TrustBar";
import { ProductCarousel } from "./ProductCarousel";
import { ProductGallery } from "./ProductGallery";
import { ProductPurchasePanel } from "./ProductPurchasePanel";

const iconByName = { "badge-check": BadgeCheck, "clock-3": Clock3, heart: Heart, "shield-check": ShieldCheck };

export function ProductDetailPage({ product, relatedProducts }: { product: Product; relatedProducts: Product[] }) {
  return <main><Container className="py-3"><Breadcrumb items={[{ href: "/parfumler", label: "Parfümler" }, { label: product.name }]} /></Container><Container className="grid gap-8 pb-9 lg:grid-cols-[1.12fr_0.88fr] lg:gap-10"><ProductGallery images={product.images} productName={product.name} /><section className="lg:pt-1"><p className="text-[0.625rem] font-semibold tracking-[0.2em] text-brand-gold uppercase">{product.productType}</p><h1 className="mt-2 font-display text-[3.5rem] leading-[0.88] text-brand-ink sm:text-[4rem]">{product.name}</h1><p className="mt-2 text-[0.625rem] font-semibold tracking-[0.12em] text-brand-muted uppercase">{product.subtitle}</p><RatingStars className="mt-4" rating={product.rating} reviewCount={product.reviewCount} /><p className="mt-4 max-w-xl text-[0.8125rem] leading-5 text-brand-muted">{product.description}</p><ProductPurchasePanel product={product} /><div className="grid gap-3 pt-5 sm:grid-cols-3">{[{ icon: Truck, title: "Ücretsiz Kargo", copy: "750₺ ve üzeri" }, { icon: Clock3, title: "Hızlı Teslimat", copy: "1–2 iş günü" }, { icon: Heart, title: "Kolay İade", copy: "14 gün içinde" }].map(({ icon: Icon, title, copy }) => <div className="flex gap-2 border-l border-brand-line pl-3" key={title}><Icon aria-hidden="true" className="size-[1.15rem] shrink-0 text-brand-gold" strokeWidth={1.4} /><p className="text-[0.6875rem] text-brand-muted"><strong className="block text-brand-ink">{title}</strong>{copy}</p></div>)}</div></section></Container><ProductScentProfile product={product} /><ProductIngredients product={product} /><ProductReviews product={product} /><ProductFaq product={product} />{relatedProducts.length ? <section className="border-t border-brand-line py-8"><Container><div className="flex items-end justify-between gap-4"><div><p className="text-[0.625rem] font-semibold tracking-[0.18em] text-brand-gold uppercase">Sizin İçin Önerilenler</p><h2 className="mt-1 font-display text-3xl text-brand-ink">Benzer İmzalar</h2></div><Link className="border-b border-brand-gold pb-1 text-[0.625rem] font-semibold tracking-[0.08em] text-brand-teal uppercase" href="/parfumler">Tümünü Gör</Link></div><div className="mt-6"><ProductCarousel cardClassName="w-[min(14rem,70vw)] [&_img]:aspect-[4/3]!" products={relatedProducts} /></div></Container></section> : null}<TrustBar items={product.benefits} /></main>;
}

function ProductScentProfile({ product }: { product: Product }) {
  const notes = [{ label: "Üst Notalar", items: product.topNotes }, { label: "Orta Notalar", items: product.middleNotes }, { label: "Dip Notalar", items: product.baseNotes }];
  return <section className="border-y border-brand-line bg-brand-paper py-8"><Container className="grid gap-7 lg:grid-cols-[1.1fr_0.9fr]"><div><p className="text-[0.625rem] font-semibold tracking-[0.18em] text-brand-gold uppercase">Koku Profili</p><h2 className="mt-1 font-display text-3xl text-brand-ink">Notaların Yolculuğu</h2><div className="mt-5 space-y-0 border-y border-brand-line">{notes.map((group, index) => <div className="grid grid-cols-[4rem_1fr] gap-4 border-brand-line py-4 not-last:border-b" key={group.label}><div className="text-[0.625rem] font-semibold tracking-[0.08em] text-brand-gold uppercase">0{index + 1}</div><div><h3 className="text-[0.625rem] font-semibold tracking-[0.1em] text-brand-ink uppercase">{group.label}</h3><p className="mt-1 text-[0.8125rem] text-brand-muted">{group.items.map((note) => note.name).join(", ")}</p></div></div>)}</div></div><div className="border border-brand-line bg-brand-ivory p-5"><h2 className="font-display text-[1.75rem] text-brand-ink">Performans</h2><PerformanceMeter label="Kalıcılık" value={product.longevity} description="8–10 Saat" /><PerformanceMeter label="Yoğunluk" value={product.intensity} description="Yüksek" /><div className="mt-6 border-t border-brand-line pt-5"><p className="text-[0.625rem] font-semibold tracking-[0.1em] text-brand-gold uppercase">Kullanım Zamanı</p><p className="mt-2 text-[0.8125rem] text-brand-muted">{product.usageTimes.map((time) => ({ day: "Gündüz", night: "Akşam", "special-occasion": "Özel Anlar" })[time]).join(" · ")}</p></div></div></Container></section>;
}

function PerformanceMeter({ description, label, value }: { description: string; label: string; value: number }) { return <div className="mt-7"><div className="flex justify-between text-xs font-semibold tracking-[0.08em] uppercase"><span>{label}</span><span className="text-brand-muted">{description}</span></div><div aria-label={`${label}: 5 üzerinden ${value}`} className="mt-3 flex gap-1" role="img">{Array.from({ length: 5 }, (_, index) => <span className={`h-1.5 flex-1 ${index < value ? "bg-brand-gold" : "bg-brand-sand-deep"}`} key={index} />)}</div></div>; }

function ProductIngredients({ product }: { product: Product }) { return <section className="border-b border-brand-line py-6"><Container><h2 className="font-display text-[1.75rem] text-brand-ink">İçerik & Uyumluluk</h2><p className="mt-2 max-w-4xl text-[0.75rem] leading-5 text-brand-muted">{product.ingredients}</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{product.compliance.map((item) => { const Icon = iconByName[item.icon as keyof typeof iconByName] ?? ShieldCheck; return <div className="flex gap-3 border border-brand-line p-3.5" key={item.id}><Icon aria-hidden="true" className="size-5 shrink-0 text-brand-gold" strokeWidth={1.35} /><div><h3 className="text-[0.625rem] font-semibold tracking-[0.08em] text-brand-ink uppercase">{item.label}</h3><p className="mt-1 text-[0.6875rem] leading-4 text-brand-muted">{item.description}</p></div></div>; })}</div></Container></section>; }

function ProductReviews({ product }: { product: Product }) { return <section className="border-b border-brand-line py-7"><Container><div className="grid gap-6 lg:grid-cols-[0.3fr_1fr]"><div><p className="text-[0.625rem] font-semibold tracking-[0.18em] text-brand-gold uppercase">Müşteri Yorumları</p><p className="mt-2 font-display text-5xl text-brand-ink">{product.rating.toFixed(1)}</p><RatingStars className="mt-1" rating={product.rating} reviewCount={product.reviewCount} /></div><div className="grid gap-3 md:grid-cols-3">{product.reviews.map((review) => <article className="border border-brand-line bg-brand-paper p-4" key={review.id}><div className="flex items-center justify-between gap-2"><h3 className="text-[0.75rem] font-semibold text-brand-ink">{review.authorName}</h3>{review.verifiedPurchase ? <span className="text-[0.5625rem] font-semibold text-brand-teal">Doğrulanmış Alıcı</span> : null}</div><RatingStars className="mt-2" rating={review.rating} showValue={false} /><p className="mt-3 text-[0.75rem] leading-5 text-brand-muted">{review.body}</p><p className="mt-3 text-[0.625rem] text-brand-muted">{review.helpfulCount} kişi faydalı buldu</p></article>)}</div></div></Container></section>; }

function ProductFaq({ product }: { product: Product }) { return <section className="py-7"><Container className="max-w-4xl"><p className="text-center text-[0.625rem] font-semibold tracking-[0.18em] text-brand-gold uppercase">Sıkça Sorulan Sorular</p><h2 className="mt-1 text-center font-display text-3xl text-brand-ink">{product.name} Hakkında</h2><div className="mt-6 divide-y divide-brand-line border-y border-brand-line">{product.faq.filter((item) => item.enabled).sort((a, b) => a.order - b.order).map((item) => <details className="group py-3.5" key={item.id}><summary className="cursor-pointer list-none pr-8 text-[0.75rem] font-medium text-brand-ink marker:content-none">{item.question}<span aria-hidden="true" className="float-right text-lg text-brand-gold group-open:rotate-45">+</span></summary><p className="pt-2 text-[0.75rem] leading-5 text-brand-muted">{item.answer}</p></details>)}</div></Container></section>; }
