import Link from "next/link";
import { ArrowRight, Clock3 } from "lucide-react";
import type { ArticleContentBlock, BlogCategory, BlogPageData, BlogPost } from "@/domain/models";
import { Container } from "@/components/ui/Container";
import { Media } from "@/components/ui/Media";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { Breadcrumb } from "@/components/ui/Breadcrumb";
import { NewsletterBanner } from "@/components/layout/NewsletterBanner";
import { ArticleCard } from "./ArticleCard";

export function BlogListingPage({ activeCategory, categories, data, featuredPost, posts }: { activeCategory?: string; categories: BlogCategory[]; data: BlogPageData; featuredPost: BlogPost | null; posts: BlogPost[] }) {
  return <main>{data.hero.enabled ? <section className="relative isolate overflow-hidden border-y border-brand-line bg-brand-sand"><Media asset={data.hero.image} className="absolute inset-0 h-full w-full object-cover object-[68%_center]" loading="eager" sizes="100vw" /><div className="absolute inset-0 bg-linear-to-r from-brand-ivory via-brand-ivory/80 to-transparent" /><Container className="relative flex min-h-[18rem] items-center py-9 lg:min-h-[20rem]"><div className="max-w-xl"><p className="text-[0.625rem] font-semibold tracking-[0.2em] text-brand-gold uppercase">{data.hero.eyebrow}</p><h1 className="mt-3 font-display text-[2.75rem] leading-[0.92] text-brand-ink sm:text-5xl">{data.hero.title}</h1><p className="mt-4 max-w-md text-[0.8125rem] leading-5 text-brand-muted">{data.hero.description}</p><Link className="mt-5 inline-flex min-h-10 items-center bg-brand-teal px-5 text-[0.625rem] font-semibold tracking-[0.08em] text-brand-ivory uppercase" href={data.hero.cta.href}>{data.hero.cta.label}<ArrowRight aria-hidden="true" className="ml-2 size-4" /></Link></div></Container></section> : null}<section className="py-7"><Container><nav aria-label="Blog kategorileri" className="flex gap-2 overflow-x-auto pb-1 [scrollbar-width:none]"><Link className={`min-h-9 shrink-0 border px-4 text-[0.625rem] font-semibold tracking-[0.08em] uppercase ${!activeCategory ? "border-brand-teal bg-brand-teal text-brand-ivory" : "border-brand-line text-brand-ink"}`} href="/blog">Tümü</Link>{categories.map((category) => <Link className={`min-h-9 shrink-0 border px-4 text-[0.625rem] font-semibold tracking-[0.08em] uppercase ${activeCategory === category.slug ? "border-brand-teal bg-brand-teal text-brand-ivory" : "border-brand-line text-brand-ink"}`} href={`/blog?category=${category.slug}`} key={category.id}>{category.name}</Link>)}</nav>{featuredPost && !activeCategory ? <div className="mt-5"><ArticleCard featured post={featuredPost} /></div> : null}<div className="mt-7" id="yazilar"><SectionHeading title={activeCategory ? `${categories.find((item) => item.slug === activeCategory)?.name ?? "Blog"} Yazıları` : "Koku Dünyasından Notlar"} /><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{posts.filter((post) => post.id !== featuredPost?.id || Boolean(activeCategory)).map((post) => <ArticleCard key={post.id} post={post} />)}</div></div></Container></section>{data.newsletter.enabled ? <NewsletterBanner description={data.newsletter.description} title={data.newsletter.title} /> : null}</main>;
}

export function BlogArticlePage({ post, relatedPosts }: { post: BlogPost; relatedPosts: BlogPost[] }) { return <main><Container className="py-4"><Breadcrumb items={[{ href: "/blog", label: "Blog" }, { label: post.title }]} /></Container><Container className="max-w-4xl pb-[var(--sv-space-2xl)]"><p className="text-xs font-semibold tracking-[0.18em] text-brand-gold uppercase">Koku Rehberi</p><h1 className="mt-4 font-display text-5xl leading-[0.94] text-brand-ink sm:text-6xl">{post.title}</h1><div className="mt-5 flex items-center gap-2 text-sm text-brand-muted"><Clock3 aria-hidden="true" className="size-4 text-brand-gold" />{post.readingTimeMinutes} dk okuma</div><Media asset={post.coverImage} className="mt-8 aspect-[16/8] border border-brand-line object-cover" loading="eager" sizes="(min-width: 1024px) 70vw, 100vw" /><article className="mx-auto mt-10 max-w-3xl text-[1.05rem] leading-8 text-brand-muted">{post.content.map((block) => <ArticleBlock block={block} key={block.id} />)}</article></Container>{relatedPosts.length ? <section className="border-y border-brand-line bg-brand-paper py-[var(--sv-space-xl)]"><Container><SectionHeading title="Benzer Yazılar" /><div className="mt-7 grid gap-4 md:grid-cols-3">{relatedPosts.map((item) => <ArticleCard key={item.id} post={item} />)}</div></Container></section> : null}</main>; }

function ArticleBlock({ block }: { block: ArticleContentBlock }) { if (block.type === "heading") { const Tag = `h${block.level}` as "h2" | "h3"; return <Tag className="mt-8 font-display text-3xl leading-tight text-brand-ink">{block.text}</Tag>; } if (block.type === "quote") return <blockquote className="my-8 border-l-2 border-brand-gold pl-5 font-display text-3xl leading-tight text-brand-ink">{block.text}{block.attribution ? <footer className="mt-3 font-sans text-sm text-brand-muted">— {block.attribution}</footer> : null}</blockquote>; if (block.type === "image") return <figure className="my-8"><Media asset={block.image} className="aspect-[16/9] object-cover" sizes="(min-width: 1024px) 50vw, 100vw" />{block.caption ? <figcaption className="mt-2 text-xs text-brand-muted">{block.caption}</figcaption> : null}</figure>; if (block.type === "callout") return <aside className="my-8 border border-brand-line bg-brand-paper p-5"><h2 className="font-display text-2xl text-brand-ink">{block.title}</h2><p className="mt-2 text-sm leading-6">{block.text}</p></aside>; return <p className="mt-5">{block.text}</p>; }
